# NumPy Intro

Curriculum related lesson: https://github.com/learn-co-students/dsc-1-08-03-intro-to-numpy-online-ds-sp-000

In [3]:
# Usually imported as `np`
import numpy as np

# For later
import pandas as pd

# Arrays

Arrays are very similar to lists but do have some extra efficiency and actions

In [4]:
# Let's define an array!
my_arr = np.array([1,2,3,4])
my_arr

array([1, 2, 3, 4])

In [5]:
# We can create numpy arrays in lots of different ways
use_range = range(10)
print('Using range: ', np.array(use_range))

use_tuple = (5,2,3)
print('Using tuples: ', np.array(use_tuple))

use_series = pd.Series([1,2,3])
print('Using pd.Series: ', np.array(use_series))

Using range:  [0 1 2 3 4 5 6 7 8 9]
Using tuples:  [5 2 3]
Using pd.Series:  [1 2 3]


## Math

### Remember Lists?
A certain syntax

In [6]:
list0 = [1,2,3]
list0 + 4

TypeError: can only concatenate list (not "int") to list

In [ ]:
list0 + [4]

In [ ]:
# What about multiplication?
print(list0 * 3)

# What about division
print(list0 / 3)

In [ ]:
# Adding lists together
list0 = [0,1,2]
list1 = [3,4,5]
print(list0)
print(list1)
print(list0 + list1)

### Looking at NumPy Arrays

In [7]:
np_arr0 = np.array(range(4))
np_arr0

array([0, 1, 2, 3])

In [8]:
# All them math
print(np_arr0 + 3)
print(np_arr0 - 3)
print(np_arr0 * 3)
print(np_arr0 / 3)

[3 4 5 6]
[-3 -2 -1  0]
[0 3 6 9]
[0.         0.33333333 0.66666667 1.        ]


In [9]:
# Adding arrays together
np_arr0 = np.array([0,1,2])
np_arr1 = np.array([3,4,5])
print(np_arr0)
print(np_arr1)
print(np_arr0 + np_arr1)

[0 1 2]
[3 4 5]
[3 5 7]


## Multidimensional

Curriculum: https://github.com/learn-co-students/dsc-1-08-04-getting-started-with-numpy-online-ds-sp-000

In [10]:
arr_2d = np.array([
    [0,1,2],
    [3,4,5],
    [6,7,8]
])

print(arr_2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
arr_3d = np.array([
    [range(0,3),range(3,6),range(6,9)],
    [range(9,12),range(12,15),range(15,18)],
    [range(18,21),range(21,24),range(24,27)]
])

print(arr_3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [12]:
print(arr_2d.shape)
print(arr_3d.shape)

(3, 3)
(3, 3, 3)


## Using some built-ins

In [13]:
#3 dimensional; 3 4x5 matrices
zeros_3d = np.zeros([3,4,5])
print(zeros_3d)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [14]:
#3 dimensional; 3 4x5 matrices
ones_3d = np.ones([3,4,5])
print(ones_3d)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [15]:
#3 dimensional; 3 4x5 matrices
full_3d = np.full([3,4,5], 27)
print(full_3d)

[[[27 27 27 27 27]
  [27 27 27 27 27]
  [27 27 27 27 27]
  [27 27 27 27 27]]

 [[27 27 27 27 27]
  [27 27 27 27 27]
  [27 27 27 27 27]
  [27 27 27 27 27]]

 [[27 27 27 27 27]
  [27 27 27 27 27]
  [27 27 27 27 27]
  [27 27 27 27 27]]]


In [16]:
# Note we can do some fun stuff with full
np.full(5, range(5))

array([0, 1, 2, 3, 4])

In [17]:
# But this won't work  with multi-dim :(
np.full([5,2], range(10))

ValueError: could not broadcast input array from shape (10) into shape (5,2)

## Slicing & Dicing

We can slice NumPy arrays but they differ from Python's lists

In [18]:
arr0 = np.random.randint(low=0, high=10, size=[5,8])
arr0

array([[7, 0, 5, 2, 7, 8, 9, 8],
       [3, 3, 9, 2, 6, 7, 9, 2],
       [0, 0, 9, 8, 3, 7, 9, 7],
       [6, 1, 5, 1, 9, 6, 8, 7],
       [1, 9, 9, 8, 0, 9, 1, 8]])

In [19]:
# Getting rows
print('first row', arr0[0])
print('last row', arr0[-1])
print('multiple rows\n', arr0[1:3])

first row [7 0 5 2 7 8 9 8]
last row [1 9 9 8 0 9 1 8]
multiple rows
 [[3 3 9 2 6 7 9 2]
 [0 0 9 8 3 7 9 7]]


In [20]:
# Selecting sub-arrays
row_start, row_end = 2, 7
col_start, col_end = 3, 6

print(
    arr0[
        row_start:row_end,
        col_start:col_end
    ]
)

[[8 3 7]
 [1 9 6]
 [8 0 9]]
