In [4]:
#Tasks
#1.Create an array of ten zeros but the fourth value which is 5
#TODO


import numpy as np
array=np.zeros(10)
almost_all_zeros_array =np.zeros(10)
almost_all_zeros_array[3] =5
print(almost_all_zeros_array)

[0. 0. 0. 5. 0. 0. 0. 0. 0. 0.]


In [6]:
#2.Create another array of ten random values
#TODO

random_array = np.random.randint(10, size=10)
print(random_array)

[4 1 0 5 1 3 9 2 1 6]


In [7]:
#3.Combine the values mathematically (addition, multiplication, etc.) to make a new array of ten values
#TODO

new_array = random_array + almost_all_zeros_array
print(new_array)


[ 4.  1.  0. 10.  1.  3.  9.  2.  1.  6.]


In [11]:

#4.[CHALLENGE!] Create a 3D array where the values represent the number of days in the month and each row represents the following months
#1st row: Jan-Apr
#2nd row: May-Aug
#3rd row: Sept-Dec

#TODO
import calendar

month_array = np.array([(calendar.month_name[1:5]), (calendar.month_name[5:9]), calendar.month_name[9:13]])
print(month_array)
print(month_array[1,1])

[['January' 'February' 'March' 'April']
 ['May' 'June' 'July' 'August']
 ['September' 'October' 'November' 'December']]
June
